### ISSUE TITLE
not an issue - question on integration with maya / modo / blender (fbx format)

### ISSUE THREAD

**Issue by 8secz-johndpope** [zhan-xu/AnimSkelVolNet#1]
Were there any attempts to spit out a skeleton / model binded to use in 3d software like autodesk maya?

https://www.youtube.com/watch?v=c538zkwxgTQ

**Comment by zhan-xu** [comment]
Hi, I just uploaded a script "maya_bind.py" which could be used to bind the predicted skeleton file with the original mesh. I use geodesic voxel binding from Maya to generate skinning weights.

**Comment by johndpope** [comment]
wow - thanks
