### ISSUE TITLE
About generating sdf files

### ISSUE THREAD

**Issue by whitealex95** [zhan-xu/AnimSkelVolNet#2]
Hi, can you tell us what method you used to generate sdf from the mesh dataset?
Methods below seems to fail
https://pypi.org/project/mesh-to-sdf/
https://github.com/christopherbatty/SDFGen

**Comment by zhan-xu** [comment]
Hi. Since this is a voxel-based method, for SDF, we first voxelize meshes by binvox (https://www.patrickmin.com/binvox/), and then convert the binary voxelized grid into SDF by simple morphological operations (see bin2sdf in gen_dataset.py).
