### ISSUE TITLE
Dataset broken link

### ISSUE THREAD

**Issue by JonnyScream** [zhan-xu/AnimSkelVolNet#3]
Using the dataset's link:
https://umass.app.box.com/s/pgm8i7of0w1om4anzl9dxignepcaanym

forwards to a page that claims:
"This shared file or folder link has been removed or is unavailable to you."

Is there an alternative?

**Comment by zhan-xu** [comment]
Thanks for reminding me. I just updated the new links.

**Comment by JonnyScream** [comment]
Hi, 
thank you very much.
