### ISSUE TITLE
Missing files mentioned in the arguments list

### ISSUE THREAD

**Issue by JonnyScream** [zhan-xu/AnimSkelVolNet#4]
Hi Zhan-xu,
Where can i find the following files, (mentioned as the arguments passed down to the 'run_trainval.py')?
'model-resource-volumetric.h5'
'model-resource-volumetric.json'

thanks.

**Comment by zhan-xu** [comment]
Hi, you need to run "python gen_dataset.py" first to create them from the data

**Comment by JonnyScream** [comment]
Got it.
Thank you.
