### ISSUE TITLE
训练好的模型文件下载损坏

### ISSUE THREAD

**Issue by zhaoguoming** [zhan-xu/AnimSkelVolNet#5]
大佬你好，我看您的这个项目工程，在readme中的Inference部分，训练好的模型下载地址中的文件下载下来后不能够解压，显示存在损坏，能否重新提交一下文件或者发送到我的邮箱1764676475@qq.com,十分感谢！请您看到后提供帮助

**Comment by zhan-xu** [comment]
hello. 这个是不需要解压的，是pytorch训练所有状态保存起来的checkpoint，可以直接在程序里读
