### ISSUE TITLE
关于文中的对比方法

### ISSUE THREAD

**Issue by zhoaliang** [zhan-xu/AnimSkelVolNet#6]
您好，请问您的“AnimSkelVolNet”文章中的两种骨骼生成对比方法“L1-median”,关于这对比方法，我的结果只有骨架，没有关节，想请问您文中关于这个方法，是如何从骨架中确定关节？

**Comment by zhoaliang** [comment]
Hello, Mr. Xv, maybe I didn't express my last question clearly. I saw your "AnimSkelVolNet" article about the "L1-median" comparison method, but I also used that method to get a curved skeleton, may I ask how you processed and simplified it to determine the joints; in Figure 7 Did you calculate the "L1-median" skeleton using the MST algorithm? Or was it generated by other methods?

**Comment by zhan-xu** [comment]
Hi I thought I replied your email... I didn't use any other methods to extract joints for L1-median. As far as I can remember, the output of L1-median has multiple segments. You can use the junction of segments as joint.

**Comment by zhoaliang** [comment]
> 
Thank you very much for your reply, maybe I found a reproduction of the "L1" method, I'll look for it again.

**Comment by Xin-97** [comment]
@zhoaliang  Hi, could you share the L1 implementation, what I found only has joints without connection. Thanks.
